linuxarm64_build_task:
  # I SHOULD NOT HARDCODE THAT ABOVE
  # If fails to build THEN check THIS OUT
  # https://cirrus-ci.com/github/AndreMikulec/testapp
  name: "arm cimg/base:edge"
  arm_container:
    image: cimg/base:edge
    cpu: 2
    # if [   +6 ms] FAILED: /tmp/cirrus-ci-build/linux/flutter/ephemeral/libflutter_linux_gtk.so
    #   then MAYBE!?!not enough memory
    memory: 2G
  timeout_in: 5m
  script:
    - uname -a
    - whoami
    - echo `pwd`
    - ls -alrt
    - echo ${PATH} || true

    #
    # uname -a
    # gcc: latest
    # Linux cirrus-ci-task-6527987532169216 5.4.209-116.367.amzn2.aarch64 #1 SMP Wed Aug 31 00:10:02 UTC 2022 aarch64 aarch64 aarch64
    # whoami
    # circleci
    # echo `pwd`
    # /tmp/cirrus-ci-build
    # echo ${PATH} || true
    # /home/circleci/bin:/home/circleci/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    #
    # EARLY OCT 2022
    # cimg/base:edge
    # https://download.docker.com/linux/ubuntu jammy InRelease
    # http://ports.ubuntu.com/ubuntu-ports jammy*
    #

    - ls -l /home/circleci/bin || true
    - ls -l /home/circleci/.local/bin || true
    - ls -l /usr/local/sbin || true
    - ls -l /usr/local/bin || true
    - ls -l /usr/sbin || true
    - ls -l /usr/bin || true
    - ls -l /sbin || true
    - ls -l /bin || true

    # OCT 2022
    # mostly from
    # Linux install
    # * Install Flutter manually * section
    # https://docs.flutter.dev/get-started/install/linux
    # . . .

    # https://zoomadmin.com/HowToInstall/UbuntuPackage/file
    - sudo apt-get update -y
    - sudo apt-get install -y file
    # ONLY if doing: Flutter `test`
    - sudo apt-get install -y libglu1-mesa

    # OTHERS
    - sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

    # THE RUNTIME END USER MAY ALSO NEED TO INSTALL
    # THE RUNTIME END USER MAY ALSO NEED TO INSTALL
    # THE RUNTIME END USER MAY ALSO NEED TO INSTALL
    # add
    # Building Linux apps with Flutter
    # * Preparing Linux apps for distribution * section
    # https://docs.flutter.dev/development/platform-integration/linux/building
    - sudo apt-get install libgtk-3-0 libblkid1 liblzma5

    # personal preference
    # https://linuxhint.com/install-7zip-compression-tool-on-ubuntu/
    # - sudo apt-get install -y 7zip-full
    # Unable to locate package 7zip-full

    # NOTE "cimg/base:edge" DOES HAVE
    # tar
    # git
    # gunzip, unzip, gzip
    #
    # A jq program is a "filter"
    # Windows
    # jq 1.6 executables for 64-bit or 32-bit.
    # https://stedolan.github.io/jq/manual/
    # jq  # determine CIRRUS_RELEASE and curl uses CIRRUS_REPO_FULL_NAME CIRRUS_TAG and possibly GITHUB_TOKEN

    # OPTION 2 OF 2
    - git clone --depth 1 --branch stable https://github.com/flutter/flutter.git  /tmp/flutter
    - export PATH="$PATH:/tmp/flutter/bin:/tmp/flutter/bin/cache/dart-sdk/bin"

    - flutter config --no-analytics
    - flutter config --no-enable-web
    - flutter config --enable-linux-desktop
    - flutter precache --linux
    - flutter doctor -v

    - which dart
    - dart --version
    - which flutter
    - flutter --version

    # - flutter create .
    # avoid "cirrus-ci-build" is not a valid Dart package name
    - flutter create --project-name $CIRRUS_REPO_NAME .

    - flutter pub get
    #
    # I SHOULD NOT HARDCODE THIS
    - flutter build linux --debug -v
    # I SHOULD NOT HARDCODE THIS
    - ls -alrt build/linux/arm64/debug/bundle
    # I SHOULD NOT HARDCODE THIS
    - ls -alrt build/linux/arm64/debug/bundle/$CIRRUS_REPO_NAME

    # I SHOULD NOT HARDCODE THIS
    - pushd build/linux/arm64/debug/bundle
    # I SHOULD NOT HARDCODE THIS
    - zip –r ${CIRRUS_REPO_NAME}_LinuxARM64_Debug.zip *
    - popd

    # env: bash\r: No such file or directory [duplicate]
    # 2015 seen 2022
    # https://stackoverflow.com/questions/29045140/env-bash-r-no-such-file-or-directory
    - sed -i $'s/\r$//' cirrus-ci-release-assets.sh
    # I SHOULD NOT HARDCODE THIS
    - chmod u+x cirrus-ci-release-assets.sh
    - ./cirrus-ci-release-assets.sh

  zipped_artifacts:

    # accepts a glob pattern of files relative to $CIRRUS_WORKING_DIR
    # https://cirrus-ci.org/guide/writing-tasks/#artifacts-instruction
    #
    # CIRRUS_WORKING_DIR	cirrus-ci-build folder inside of a system's temporary folder
    # Working directory where Cirrus CI executes builds.
    # Default to cirrus-ci-build folder inside of a system's temporary folder.
    # https://cirrus-ci.org/guide/writing-tasks/#environment-variables
    #
    path: "*.zip"
    type: application/zip


# I SHOULD NOT HARDCODE THIS
linuxarm64_release_task:
#
# Release Assets
# https://cirrus-ci.org/examples/#release-assets
#
# some default environment variables are pre-defined
#   CIRRUS_TAG
#     Tag name if current build was triggered by a new tag. For example v1.0
#   CIRRUS_RELEASE
#     GitHub Release id if current tag was created for a release. Handy for uploading release assets.
# https://cirrus-ci.org/guide/writing-tasks/
#
# CIRRUS_TAG	Tag name if current build was triggered by a new tag. For example v1.0
# CIRRUS_RELEASE	GitHub Release id if current tag was created for a release
# https://cirrus-ci.org/guide/writing-tasks/#environment-variables
#
#   # the case seems, in a separate task,
#   #  that I have to set this CIRRUS_RELEASE value myself
#   filename:.cirrus.yml CIRRUS_RELEASE
#   https://github.com/search?q=filename%3A.cirrus.yml+CIRRUS_RELEASE
#
# Secured Variables (per repository)
#   https://cirrus-ci.org/guide/writing-tasks/#encrypted-variables
#   FROM
#     https://cirrus-ci.com/settings/github/AndreMikulec
#       Owner-Level Secured Variables
#       NOTE . . .
#       API Settings
#         Need an API token for scripts or testing?
#           https://cirrus-ci.org/api/
#             Cirrus CI exposes GraphQL API for integrators to use through https://api.cirrus-ci.com/graphql endpoint.
# OR FROM
#   https://cirrus-ci.com/github/AndreMikulec/REPOSITORY -> Settings
#     Secured Variables
#   https://cirrus-ci.com/github/AndreMikulec/testapp
#     Secured Variables
#
  ## only_if: $CIRRUS_TAG != ''
  env:
    # That's why you need to create a personal access token with full access to repo scope. (NOT_YET_VERIFIED)
    # https://cirrus-ci.org/examples/#release-assets
    # Owner-Level Secured Variables (value of https://github.com/settings/tokens GITHUB_ACTIONS_CREATE_RELEASE_REPO)
    GITHUB_TOKEN: ENCRYPTED[!1a8e14b4948b6beae2583951ab1abaf3800656297eabe0d877e918bb80050524248dbb11e6b5d6a2551befdd869a8100!]


